title: Marketplace Documentation
description: Marketplace documentation
theme: just-the-docs

url: https://marketplace-documentation.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
